#!/bin/bash

# Usage : ./start-dcvm jvmName

java -ea -cp 'jars/*' -Djava.security.manager \
     -Djava.security.policy=dcvm.policy \
     fr.sorbonne_u.sylalexcenter.tests.TestAdmissionControllerMultiJVM $1 config.xml
